services:
  - type: web
    name: vip-human-god
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"